AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Contact Api

Resources:
  VerifyCaptcha:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: captcha.verify
      Runtime: nodejs16.x
      MemorySize: 1024
      Timeout: 20
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      Events:
        APIRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref ContactApi

  ContactApiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-8bf54bf6
      GroupDescription: Allows access over 443
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  ContactApiAccessEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: vpc-8bf54bf6
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.execute-api"
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - subnet-d2ffcd9f
        - subnet-8babc4d4
      SecurityGroupIds:
        - !Ref ContactApiSecurityGroup

  ContactApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      MethodSettings:
        - HttpMethod: POST
          ResourcePath: /
      EndpointConfiguration: PRIVATE
      DefinitionBody:
        swagger: 2.0
        info:
          title: ContactApi
        basePath: /Dev
        schemes:
          - https
        x-amazon-apigateway-policy:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal: "*"
              Action:
                - "execute-api:Invoke"
              Resource: "execute-api:/*"
              Condition:
                StringEquals:
                  aws:sourceVpce: !Ref ContactApiAccessEndpoint
        paths:
          /:
            post:
              produces:
                - application/json
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                uri:
                  !Join [
                    "",
                    [
                      !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:",
                      !Ref VerifyCaptcha,
                      "/invocations",
                    ],
                  ]
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: AWS_PROXY

Outputs:
  ContactApi:
    Description: "API Gateway endpoint URL for Dev stage"
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
  VerifyCaptcha:
    Description: "Lambda Function ARN"
    Value: !GetAtt VerifyCaptcha.Arn
